version: '3.9'


services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/server/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - laravelom

    db:
        image: postgres
        container_name: ${APP_NAME}_db
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
            - "3457:3452"
        networks:
            - laravelom

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        container_name: ${APP_NAME}_php
        ports:
            - "9004:9004"
        networks:
            - laravelom

    composer:
        image: composer:latest
        container_name: ${APP_NAME}_composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db
            - php
        networks:
            - laravelom
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - laravelom

networks:
    laravelom:
